---
version: '3.4'
services:
  ${acs.host}:
    image: authentication-hmac-platform:development
    build:
      dockerfile: ./Dockerfile
      context: ../../authentication-hmac-platform-docker/target
    environment:
      CATALINA_OPTS : "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
      JAVA_OPTS : "-Djavamelody.authorized-users=monitor:monitor"
    volumes:
      - authentication-hmac-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - ${db.host}
    ports:
      - 8000:8000
    networks:
      - backend

  ${share.host}:
    image: authentication-hmac-share:development
    build:
      dockerfile: ./Dockerfile
      context: ../../authentication-hmac-share-docker/target
    environment:
      REPO_HOST: ${acs.host}
      REPO_PORT: 8080
    depends_on:
      - ${acs.host}
    networks:
      - backend

  ${db.host}:
    image: ${docker.postgres.image}:${docker.postgres.version}
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - authentication-hmac-db-volume:/var/lib/postgresql/data
    networks:
      - backend

  ${solr.host}:
    image: ${docker.solr.image}:${docker.solr.version}
    environment:
      SOLR_ALFRESCO_HOST: ${acs.host}
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: ${solr.host}
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: none
    volumes:
      - authentication-hmac-solr-contentstore-volume:/opt/alfresco-search-services/contentstore
      - authentication-hmac-solr-data-volume:/opt/alfresco-search-services/data
      - authentication-hmac-solr-keystores-volume:/opt/alfresco-search-services/keystores
      - authentication-hmac-solr-solrhome-volume:/opt/alfresco-search-services/solrhome
    depends_on:
      - ${acs.host}
    networks:
      - backend

  ${activemq.host}:
    image: ${docker.activemq.image}:${docker.activemq.version}
    depends_on:
      - ${acs.host}
    volumes:
      - authentication-hmac-activemq-volume:/opt/activemq/conf
    networks:
      - backend

  ${transform-core-aio.host}:
    image: ${docker.transform-core-aio.image}:${docker.transform-core-aio.version}
    depends_on:
      - ${acs.host}
      - ${activemq.host}
    networks:
      - backend

  ${nginx.host}:
    image: authentication-hmac:development
    build:
      dockerfile: ./Dockerfile
      context: ../../authentication-hmac-nginx-docker/target
    environment:
      PORT: 8080
      PROXY_HOST_ADF: http://${public.host}:8080/demo
    ports:
      - "${public.port}:8080"
    depends_on:
      - ${acs.host}
      - ${share.host}
    networks:
      - backend

volumes:
  authentication-hmac-acs-volume:
  authentication-hmac-db-volume:
  authentication-hmac-activemq-volume:
  authentication-hmac-solr-contentstore-volume:
  authentication-hmac-solr-data-volume:
  authentication-hmac-solr-keystores-volume:
  authentication-hmac-solr-solrhome-volume:

networks:
  backend:
